-- 코드를 작성해주세요
SELECT D.DEPT_ID, D.DEPT_NAME_EN, N.AVG_SAL AS AVG_SAL
FROM HR_DEPARTMENT D
JOIN (SELECT ROUND(AVG(SAL)) AS AVG_SAL, DEPT_ID FROM HR_EMPLOYEES GROUP BY DEPT_ID) AS N
ON D.DEPT_ID = N.DEPT_ID
ORDER BY AVG_SAL DESC
# SELECT AVG(SAL) AS AVG_SAL, DEPT_ID FROM HR_EMPLOYEES GROUP BY DEPT_ID